# JSON examples and exercise
****
+ get familiar with packages for dealing with JSON
+ study examples with JSON strings and files 
+ work on exercise to be completed and submitted 
****
+ reference: http://pandas.pydata.org/pandas-docs/stable/io.html#io-json-reader
+ data source: http://jsonstudio.com/resources/
****

In [3]:
import pandas as pd

## imports for Python, Pandas

In [33]:
import json
from pandas.io.json import json_normalize

## JSON example, with string

+ demonstrates creation of normalized dataframes (tables) from nested json string
+ source: http://pandas.pydata.org/pandas-docs/stable/io.html#normalization

In [4]:
# define json string
data = [{'state': 'Florida', 
         'shortname': 'FL',
         'info': {'governor': 'Rick Scott'},
         'counties': [{'name': 'Dade', 'population': 12345},
                      {'name': 'Broward', 'population': 40000},
                      {'name': 'Palm Beach', 'population': 60000}]},
        {'state': 'Ohio',
         'shortname': 'OH',
         'info': {'governor': 'John Kasich'},
         'counties': [{'name': 'Summit', 'population': 1234},
                      {'name': 'Cuyahoga', 'population': 1337}]}]

In [7]:
# use normalization to create tables from nested element
json_normalize(data, 'counties')

         name  population
0        Dade       12345
1     Broward       40000
2  Palm Beach       60000
3      Summit        1234
4    Cuyahoga        1337

In [8]:
# further populate tables created from nested element
json_normalize(data, 'counties', ['state', 'shortname', ['info', 'governor']])

         name  population info.governor    state shortname
0        Dade       12345    Rick Scott  Florida        FL
1     Broward       40000    Rick Scott  Florida        FL
2  Palm Beach       60000    Rick Scott  Florida        FL
3      Summit        1234   John Kasich     Ohio        OH
4    Cuyahoga        1337   John Kasich     Ohio        OH

****
## JSON example, with file

+ demonstrates reading in a json file as a string and as a table
+ uses small sample file containing data about projects funded by the World Bank 
+ data source: http://jsonstudio.com/resources/

In [9]:
# load json as string
json.load((open('data/world_bank_projects_less.json')))

[{u'_id': {u'$oid': u'52b213b38594d8a2be17c780'},
  u'approvalfy': 1999,
  u'board_approval_month': u'November',
  u'boardapprovaldate': u'2013-11-12T00:00:00Z',
  u'borrower': u'FEDERAL DEMOCRATIC REPUBLIC OF ETHIOPIA',
  u'closingdate': u'2018-07-07T00:00:00Z',
  u'country_namecode': u'Federal Democratic Republic of Ethiopia!$!ET',
  u'countrycode': u'ET',
  u'countryname': u'Federal Democratic Republic of Ethiopia',
  u'countryshortname': u'Ethiopia',
  u'docty': u'Project Information Document,Indigenous Peoples Plan,Project Information Document',
  u'envassesmentcategorycode': u'C',
  u'grantamt': 0,
  u'ibrdcommamt': 0,
  u'id': u'P129828',
  u'idacommamt': 130000000,
  u'impagency': u'MINISTRY OF EDUCATION',
  u'lendinginstr': u'Investment Project Financing',
  u'lendinginstrtype': u'IN',
  u'lendprojectcost': 550000000,
  u'majorsector_percent': [{u'Name': u'Education', u'Percent': 46},
   {u'Name': u'Education', u'Percent': 26},
   {u'Name': u'Public Administration, Law, and Justice', u'Percent': 16},
   {u'Name': u'Education', u'Percent': 12}],
  u'mjsector_namecode': [{u'code': u'EX', u'name': u'Education'},
   {u'code': u'EX', u'name': u'Education'},
   {u'code': u'BX', u'name': u'Public Administration, Law, and Justice'},
   {u'code': u'EX', u'name': u'Education'}],
  u'mjtheme': [u'Human development'],
  u'mjtheme_namecode': [{u'code': u'8', u'name': u'Human development'},
   {u'code': u'11', u'name': u''}],
  u'mjthemecode': u'8,11',
  u'prodline': u'PE',
  u'prodlinetext': u'IBRD/IDA',
  u'productlinetype': u'L',
  u'project_abstract': {u'cdata': u'The development objective of the Second Phase of General Education Quality Improvement Project for Ethiopia is to improve learning conditions in primary and secondary schools and strengthen institutions at different levels of educational administration. The project has six components. The first component is curriculum, textbooks, assessment, examinations, and inspection. This component will support improvement of learning conditions in grades KG-12 by providing increased access to teaching and learning materials and through improvements to the curriculum by assessing the strengths and weaknesses of the current curriculum. This component has following four sub-components: (i) curriculum reform and implementation; (ii) teaching and learning materials; (iii) assessment and examinations; and (iv) inspection. The second component is teacher development program (TDP). This component will support improvements in learning conditions in both primary and secondary schools by advancing the quality of teaching in general education through: (a) enhancing the training of pre-service teachers in teacher education institutions; and (b) improving the quality of in-service teacher training. This component has following three sub-components: (i) pre-service teacher training; (ii) in-service teacher training; and (iii) licensing and relicensing of teachers and school leaders. The third component is school improvement plan. This component will support the strengthening of school planning in order to improve learning outcomes, and to partly fund the school improvement plans through school grants. It has following two sub-components: (i) school improvement plan; and (ii) school grants. The fourth component is management and capacity building, including education management information systems (EMIS). This component will support management and capacity building aspect of the project. This component has following three sub-components: (i) capacity building for education planning and management; (ii) capacity building for school planning and management; and (iii) EMIS. The fifth component is improving the quality of learning and teaching in secondary schools and universities through the use of information and communications technology (ICT). It has following five sub-components: (i) national policy and institution for ICT in general education; (ii) national ICT infrastructure improvement plan for general education; (iii) develop an integrated monitoring, evaluation, and learning system specifically for the ICT component; (iv) teacher professional development in the use of ICT; and (v) provision of limited number of e-Braille display readers with the possibility to scale up to all secondary education schools based on the successful implementation and usage of the readers. The sixth component is program coordination, monitoring and evaluation, and communication. It will support institutional strengthening by developing capacities in all aspects of program coordination, monitoring and evaluation; a new sub-component on communications will support information sharing for better management and accountability. It has following three sub-components: (i) program coordination; (ii) monitoring and evaluation (M and E); and (iii) communication.'},
  u'project_name': u'Ethiopia General Education Quality Improvement Project II',
  u'projectdocs': [{u'DocDate': u'28-AUG-2013',
    u'DocType': u'PID',
    u'DocTypeDesc': u'Project Information Document (PID),  Vol.',
    u'DocURL': u'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=090224b081e545fb_1_0',
    u'EntityID': u'090224b081e545fb_1_0'},
   {u'DocDate': u'01-JUL-2013',
    u'DocType': u'IP',
    u'DocTypeDesc': u'Indigenous Peoples Plan (IP),  Vol.1 of 1',
    u'DocURL': u'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=000442464_20130920111729',
    u'EntityID': u'000442464_20130920111729'},
   {u'DocDate': u'22-NOV-2012',
    u'DocType': u'PID',
    u'DocTypeDesc': u'Project Information Document (PID),  Vol.',
    u'DocURL': u'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=090224b0817b19e2_1_0',
    u'EntityID': u'090224b0817b19e2_1_0'}],
  u'projectfinancialtype': u'IDA',
  u'projectstatusdisplay': u'Active',
  u'regionname': u'Africa',
  u'sector': [{u'Name': u'Primary education'},
   {u'Name': u'Secondary education'},
   {u'Name': u'Public administration- Other social services'},
   {u'Name': u'Tertiary education'}],
  u'sector1': {u'Name': u'Primary education', u'Percent': 46},
  u'sector2': {u'Name': u'Secondary education', u'Percent': 26},
  u'sector3': {u'Name': u'Public administration- Other social services',
   u'Percent': 16},
  u'sector4': {u'Name': u'Tertiary education', u'Percent': 12},
  u'sector_namecode': [{u'code': u'EP', u'name': u'Primary education'},
   {u'code': u'ES', u'name': u'Secondary education'},
   {u'code': u'BS', u'name': u'Public administration- Other social services'},
   {u'code': u'ET', u'name': u'Tertiary education'}],
  u'sectorcode': u'ET,BS,ES,EP',
  u'source': u'IBRD',
  u'status': u'Active',
  u'supplementprojectflg': u'N',
  u'theme1': {u'Name': u'Education for all', u'Percent': 100},
  u'theme_namecode': [{u'code': u'65', u'name': u'Education for all'}],
  u'themecode': u'65',
  u'totalamt': 130000000,
  u'totalcommamt': 130000000,
  u'url': u'http://www.worldbank.org/projects/P129828/ethiopia-general-education-quality-improvement-project-ii?lang=en'},
 {u'_id': {u'$oid': u'52b213b38594d8a2be17c781'},
  u'approvalfy': 2015,
  u'board_approval_month': u'November',
  u'boardapprovaldate': u'2013-11-04T00:00:00Z',
  u'borrower': u'GOVERNMENT OF TUNISIA',
  u'country_namecode': u'Republic of Tunisia!$!TN',
  u'countrycode': u'TN',
  u'countryname': u'Republic of Tunisia',
  u'countryshortname': u'Tunisia',
  u'docty': u'Project Information Document,Integrated Safeguards Data Sheet,Integrated Safeguards Data Sheet,Project Information Document,Integrated Safeguards Data Sheet,Project Information Document',
  u'envassesmentcategorycode': u'C',
  u'grantamt': 4700000,
  u'ibrdcommamt': 0,
  u'id': u'P144674',
  u'idacommamt': 0,
  u'impagency': u'MINISTRY OF FINANCE',
  u'lendinginstr': u'Specific Investment Loan',
  u'lendinginstrtype': u'IN',
  u'lendprojectcost': 5700000,
  u'majorsector_percent': [{u'Name': u'Public Administration, Law, and Justice',
    u'Percent': 70},
   {u'Name': u'Public Administration, Law, and Justice', u'Percent': 30}],
  u'mjsector_namecode': [{u'code': u'BX',
    u'name': u'Public Administration, Law, and Justice'},
   {u'code': u'BX', u'name': u'Public Administration, Law, and Justice'}],
  u'mjtheme': [u'Economic management',
   u'Social protection and risk management'],
  u'mjtheme_namecode': [{u'code': u'1', u'name': u'Economic management'},
   {u'code': u'6', u'name': u'Social protection and risk management'}],
  u'mjthemecode': u'1,6',
  u'prodline': u'RE',
  u'prodlinetext': u'Recipient Executed Activities',
  u'productlinetype': u'L',
  u'project_name': u'TN: DTF Social Protection Reforms Support',
  u'projectdocs': [{u'DocDate': u'29-MAR-2013',
    u'DocType': u'PID',
    u'DocTypeDesc': u'Project Information Document (PID),  Vol.1 of 1',
    u'DocURL': u'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=000333037_20131024115616',
    u'EntityID': u'000333037_20131024115616'},
   {u'DocDate': u'29-MAR-2013',
    u'DocType': u'ISDS',
    u'DocTypeDesc': u'Integrated Safeguards Data Sheet (ISDS),  Vol.1 of 1',
    u'DocURL': u'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=000356161_20131024151611',
    u'EntityID': u'000356161_20131024151611'},
   {u'DocDate': u'29-MAR-2013',
    u'DocType': u'ISDS',
    u'DocTypeDesc': u'Integrated Safeguards Data Sheet (ISDS),  Vol.1 of 1',
    u'DocURL': u'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=000442464_20131031112136',
    u'EntityID': u'000442464_20131031112136'},
   {u'DocDate': u'29-MAR-2013',
    u'DocType': u'PID',
    u'DocTypeDesc': u'Project Information Document (PID),  Vol.1 of 1',
    u'DocURL': u'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=000333037_20131031105716',
    u'EntityID': u'000333037_20131031105716'},
   {u'DocDate': u'16-JAN-2013',
    u'DocType': u'ISDS',
    u'DocTypeDesc': u'Integrated Safeguards Data Sheet (ISDS),  Vol.1 of 1',
    u'DocURL': u'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=000356161_20130305113209',
    u'EntityID': u'000356161_20130305113209'},
   {u'DocDate': u'16-JAN-2013',
    u'DocType': u'PID',
    u'DocTypeDesc': u'Project Information Document (PID),  Vol.1 of 1',
    u'DocURL': u'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=000356161_20130305113716',
    u'EntityID': u'000356161_20130305113716'}],
  u'projectfinancialtype': u'OTHER',
  u'projectstatusdisplay': u'Active',
  u'regionname': u'Middle East and North Africa',
  u'sector': [{u'Name': u'Public administration- Other social services'},
   {u'Name': u'General public administration sector'}],
  u'sector1': {u'Name': u'Public administration- Other social services',
   u'Percent': 70},
  u'sector2': {u'Name': u'General public administration sector',
   u'Percent': 30},
  u'sector_namecode': [{u'code': u'BS',
    u'name': u'Public administration- Other social services'},
   {u'code': u'BZ', u'name': u'General public administration sector'}],
  u'sectorcode': u'BZ,BS',
  u'source': u'IBRD',
  u'status': u'Active',
  u'supplementprojectflg': u'N',
  u'theme1': {u'Name': u'Other economic management', u'Percent': 30},
  u'theme_namecode': [{u'code': u'24', u'name': u'Other economic management'},
   {u'code': u'54', u'name': u'Social safety nets'}],
  u'themecode': u'54,24',
  u'totalamt': 0,
  u'totalcommamt': 4700000,
  u'url': u'http://www.worldbank.org/projects/P144674?lang=en'}]

In [10]:
# load as Pandas dataframe
sample_json_df = pd.read_json('data/world_bank_projects_less.json')
sample_json_df

,_id,approvalfy,board_approval_month,boardapprovaldate,borrower,closingdate,country_namecode,countrycode,countryname,countryshortname,...,sectorcode,source,status,supplementprojectflg,theme1,theme_namecode,themecode,totalamt,totalcommamt,url
0,{u'$oid': u'52b213b38594d8a2be17c780'},1999,November,2013-11-12T00:00:00Z,FEDERAL DEMOCRATIC REPUBLIC OF ETHIOPIA,2018-07-07T00:00:00Z,Federal Democratic Republic of Ethiopia!$!ET,ET,Federal Democratic Republic of Ethiopia,Ethiopia,...,"ET,BS,ES,EP",IBRD,Active,N,"{u'Percent': 100, u'Name': u'Education for all'}","[{u'code': u'65', u'name': u'Education for all'}]",65,130000000,130000000,http://www.worldbank.org/projects/P129828/ethi...
1,{u'$oid': u'52b213b38594d8a2be17c781'},2015,November,2013-11-04T00:00:00Z,GOVERNMENT OF TUNISIA,NaN,Republic of Tunisia!$!TN,TN,Republic of Tunisia,Tunisia,...,"BZ,BS",IBRD,Active,N,"{u'Percent': 30, u'Name': u'Other economic man...","[{u'code': u'24', u'name': u'Other economic ma...","54,24",0,4700000,http://www.worldbank.org/projects/P144674?lang=en

****
## JSON exercise

Using data in file 'data/world_bank_projects.json' and the techniques demonstrated above,
1. Find the 10 countries with most projects
2. Find the top 10 major project themes (using column 'mjtheme_namecode')
3. In 2. above you will notice that some entries have only the code and the name is missing. Create a dataframe with the missing names filled in.

# 1.Find the 10 countries with most projects

In [4]:
import pandas as pd
import json
from pandas.io.json import json_normalize

In [5]:
json_df=pd.read_json('world_bank_projects.json')

In [6]:
json_df.head()

,_id,approvalfy,board_approval_month,boardapprovaldate,borrower,closingdate,country_namecode,countrycode,countryname,countryshortname,...,sectorcode,source,status,supplementprojectflg,theme1,theme_namecode,themecode,totalamt,totalcommamt,url
0,{'$oid': '52b213b38594d8a2be17c780'},1999,November,2013-11-12T00:00:00Z,FEDERAL DEMOCRATIC REPUBLIC OF ETHIOPIA,2018-07-07T00:00:00Z,Federal Democratic Republic of Ethiopia!$!ET,ET,Federal Democratic Republic of Ethiopia,Ethiopia,...,"ET,BS,ES,EP",IBRD,Active,N,"{'Percent': 100, 'Name': 'Education for all'}","[{'code': '65', 'name': 'Education for all'}]",65,130000000,130000000,http://www.worldbank.org/projects/P129828/ethi...
1,{'$oid': '52b213b38594d8a2be17c781'},2015,November,2013-11-04T00:00:00Z,GOVERNMENT OF TUNISIA,NaN,Republic of Tunisia!$!TN,TN,Republic of Tunisia,Tunisia,...,"BZ,BS",IBRD,Active,N,"{'Percent': 30, 'Name': 'Other economic manage...","[{'code': '24', 'name': 'Other economic manage...","54,24",0,4700000,http://www.worldbank.org/projects/P144674?lang=en
2,{'$oid': '52b213b38594d8a2be17c782'},2014,November,2013-11-01T00:00:00Z,MINISTRY OF FINANCE AND ECONOMIC DEVEL,NaN,Tuvalu!$!TV,TV,Tuvalu,Tuvalu,...,TI,IBRD,Active,Y,"{'Percent': 46, 'Name': 'Regional integration'}","[{'code': '47', 'name': 'Regional integration'...","52,81,25,47",6060000,6060000,http://www.worldbank.org/projects/P145310?lang=en
3,{'$oid': '52b213b38594d8a2be17c783'},2014,October,2013-10-31T00:00:00Z,MIN. OF PLANNING AND INT'L COOPERATION,NaN,Republic of Yemen!$!RY,RY,Republic of Yemen,"Yemen, Republic of",...,JB,IBRD,Active,N,"{'Percent': 50, 'Name': 'Participation and civ...","[{'code': '57', 'name': 'Participation and civ...","59,57",0,1500000,http://www.worldbank.org/projects/P144665?lang=en
4,{'$oid': '52b213b38594d8a2be17c784'},2014,October,2013-10-31T00:00:00Z,MINISTRY OF FINANCE,2019-04-30T00:00:00Z,Kingdom of Lesotho!$!LS,LS,Kingdom of Lesotho,Lesotho,...,"FH,YW,YZ",IBRD,Active,N,"{'Percent': 30, 'Name': 'Export development an...","[{'code': '45', 'name': 'Export development an...","41,45",13100000,13100000,http://www.worldbank.org/projects/P144933/seco...

In [13]:
print(json_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 50 columns):
_id                         500 non-null object
approvalfy                  500 non-null int64
board_approval_month        500 non-null object
boardapprovaldate           500 non-null object
borrower                    485 non-null object
closingdate                 370 non-null object
country_namecode            500 non-null object
countrycode                 500 non-null object
countryname                 500 non-null object
countryshortname            500 non-null object
docty                       446 non-null object
envassesmentcategorycode    430 non-null object
grantamt                    500 non-null int64
ibrdcommamt                 500 non-null int64
id                          500 non-null object
idacommamt                  500 non-null int64
impagency                   472 non-null object
lendinginstr                495 non-null object
lendinginstrtype            495 non-null object
lendprojectcost             500 non-null int64
majorsector_percent         500 non-null object
mjsector_namecode           500 non-null object
mjtheme                     491 non-null object
mjtheme_namecode            500 non-null object
mjthemecode                 500 non-null object
prodline                    500 non-null object
prodlinetext                500 non-null object
productlinetype             500 non-null object
project_abstract            362 non-null object
project_name                500 non-null object
projectdocs                 446 non-null object
projectfinancialtype        500 non-null object
projectstatusdisplay        500 non-null object
regionname                  500 non-null object
sector                      500 non-null object
sector1                     500 non-null object
sector2                     380 non-null object
sector3                     265 non-null object
sector4                     174 non-null object
sector_namecode             500 non-null object
sectorcode                  500 non-null object
source                      500 non-null object
status                      500 non-null object
supplementprojectflg        498 non-null object
theme1                      500 non-null object
theme_namecode              491 non-null object
themecode                   491 non-null object
totalamt                    500 non-null int64
totalcommamt                500 non-null int64
url                         500 non-null object
dtypes: int64(7), object(43)
memory usage: 195.4+ KB
None

In [14]:
json_df_s=json_df[['countryname','mjtheme_namecode','mjtheme','mjthemecode']]

In [15]:
print(json_df_s.head())

                               countryname  \
0  Federal Democratic Republic of Ethiopia
1                      Republic of Tunisia
2                                   Tuvalu
3                        Republic of Yemen
4                       Kingdom of Lesotho

                                    mjtheme_namecode  \
0  [{'code': '8', 'name': 'Human development'}, {...
1  [{'code': '1', 'name': 'Economic management'},...
2  [{'code': '5', 'name': 'Trade and integration'...
3  [{'code': '7', 'name': 'Social dev/gender/incl...
4  [{'code': '5', 'name': 'Trade and integration'...

                                             mjtheme mjthemecode
0                                [Human development]        8,11
1  [Economic management, Social protection and ri...         1,6
2  [Trade and integration, Public sector governan...    5,2,11,6
3  [Social dev/gender/inclusion, Social dev/gende...         7,7
4  [Trade and integration, Financial and private ...         5,4

In [16]:
## make sure no duplicates in the data(through project ID)
json_df_id=json_df['_id'].astype(str)

In [17]:
json_df_id.drop_duplicates()

0      {'$oid': '52b213b38594d8a2be17c780'}
1      {'$oid': '52b213b38594d8a2be17c781'}
2      {'$oid': '52b213b38594d8a2be17c782'}
3      {'$oid': '52b213b38594d8a2be17c783'}
4      {'$oid': '52b213b38594d8a2be17c784'}
5      {'$oid': '52b213b38594d8a2be17c785'}
6      {'$oid': '52b213b38594d8a2be17c786'}
7      {'$oid': '52b213b38594d8a2be17c787'}
8      {'$oid': '52b213b38594d8a2be17c788'}
9      {'$oid': '52b213b38594d8a2be17c789'}
10     {'$oid': '52b213b38594d8a2be17c78a'}
11     {'$oid': '52b213b38594d8a2be17c78b'}
12     {'$oid': '52b213b38594d8a2be17c78c'}
13     {'$oid': '52b213b38594d8a2be17c78d'}
14     {'$oid': '52b213b38594d8a2be17c78e'}
15     {'$oid': '52b213b38594d8a2be17c78f'}
16     {'$oid': '52b213b38594d8a2be17c790'}
17     {'$oid': '52b213b38594d8a2be17c791'}
18     {'$oid': '52b213b38594d8a2be17c792'}
19     {'$oid': '52b213b38594d8a2be17c793'}
20     {'$oid': '52b213b38594d8a2be17c794'}
21     {'$oid': '52b213b38594d8a2be17c795'}
22     {'$oid': '52b213b38594d8a2be17c796'}
23     {'$oid': '52b213b38594d8a2be17c797'}
24     {'$oid': '52b213b38594d8a2be17c798'}
25     {'$oid': '52b213b38594d8a2be17c799'}
26     {'$oid': '52b213b38594d8a2be17c79a'}
27     {'$oid': '52b213b38594d8a2be17c79b'}
28     {'$oid': '52b213b38594d8a2be17c79c'}
29     {'$oid': '52b213b38594d8a2be17c79d'}
                       ...
470    {'$oid': '52b213b38594d8a2be17c956'}
471    {'$oid': '52b213b38594d8a2be17c957'}
472    {'$oid': '52b213b38594d8a2be17c958'}
473    {'$oid': '52b213b38594d8a2be17c959'}
474    {'$oid': '52b213b38594d8a2be17c95a'}
475    {'$oid': '52b213b38594d8a2be17c95b'}
476    {'$oid': '52b213b38594d8a2be17c95c'}
477    {'$oid': '52b213b38594d8a2be17c95d'}
478    {'$oid': '52b213b38594d8a2be17c95e'}
479    {'$oid': '52b213b38594d8a2be17c95f'}
480    {'$oid': '52b213b38594d8a2be17c960'}
481    {'$oid': '52b213b38594d8a2be17c961'}
482    {'$oid': '52b213b38594d8a2be17c962'}
483    {'$oid': '52b213b38594d8a2be17c963'}
484    {'$oid': '52b213b38594d8a2be17c964'}
485    {'$oid': '52b213b38594d8a2be17c965'}
486    {'$oid': '52b213b38594d8a2be17c966'}
487    {'$oid': '52b213b38594d8a2be17c967'}
488    {'$oid': '52b213b38594d8a2be17c968'}
489    {'$oid': '52b213b38594d8a2be17c969'}
490    {'$oid': '52b213b38594d8a2be17c96a'}
491    {'$oid': '52b213b38594d8a2be17c96b'}
492    {'$oid': '52b213b38594d8a2be17c96c'}
493    {'$oid': '52b213b38594d8a2be17c96d'}
494    {'$oid': '52b213b38594d8a2be17c96e'}
495    {'$oid': '52b213b38594d8a2be17c96f'}
496    {'$oid': '52b213b38594d8a2be17c970'}
497    {'$oid': '52b213b38594d8a2be17c971'}
498    {'$oid': '52b213b38594d8a2be17c972'}
499    {'$oid': '52b213b38594d8a2be17c973'}
Name: _id, Length: 500, dtype: object

In [18]:
print("Top 10 countries with most projects : " )
print(json_df_s.groupby('countryname').size().sort_values(ascending=False).head(10))

Top 10 countries with most projects :
countryname
People's Republic of China         19
Republic of Indonesia              19
Socialist Republic of Vietnam      17
Republic of India                  16
Republic of Yemen                  13
Nepal                              12
People's Republic of Bangladesh    12
Kingdom of Morocco                 12
Africa                             11
Republic of Mozambique             11
dtype: int64

# 2.Find the top 10 major project themes (using column 'mjtheme_namecode')

In [19]:
mj_name= json_df_s['mjtheme_namecode']

In [38]:
print(mj_name.head())

0    [{'code': '8', 'name': 'Human development'}, {...
1    [{'code': '1', 'name': 'Economic management'},...
2    [{'code': '5', 'name': 'Trade and integration'...
3    [{'code': '7', 'name': 'Social dev/gender/incl...
4    [{'code': '5', 'name': 'Trade and integration'...
Name: mjtheme_namecode, dtype: object

In [20]:
mj_df = json.load((open('world_bank_projects.json')))
mj_df1=json_normalize(mj_df,'mjtheme_namecode')

In [21]:
print(mj_df1.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1499 entries, 0 to 1498
Data columns (total 2 columns):
code    1499 non-null object
name    1499 non-null object
dtypes: object(2)
memory usage: 23.5+ KB
None

In [22]:
print(mj_df1)

     code                                          name
0       8                             Human development
1      11
2       1                           Economic management
3       6         Social protection and risk management
4       5                         Trade and integration
5       2                      Public sector governance
6      11  Environment and natural resources management
7       6         Social protection and risk management
8       7                   Social dev/gender/inclusion
9       7                   Social dev/gender/inclusion
10      5                         Trade and integration
11      4      Financial and private sector development
12      6         Social protection and risk management
13      6
14      2                      Public sector governance
15      4      Financial and private sector development
16     11  Environment and natural resources management
17      8
18     10                             Rural development
19      7
20      2                      Public sector governance
21      2                      Public sector governance
22      2                      Public sector governance
23     10                             Rural development
24      2
25     10                             Rural development
26      6         Social protection and risk management
27      6         Social protection and risk management
28     11  Environment and natural resources management
29      4
...   ...                                           ...
1469    8                             Human development
1470    9                             Urban development
1471    6         Social protection and risk management
1472    6         Social protection and risk management
1473    9                             Urban development
1474    2                      Public sector governance
1475    2                      Public sector governance
1476   10                             Rural development
1477   11
1478    8                             Human development
1479    7                   Social dev/gender/inclusion
1480   11  Environment and natural resources management
1481    5
1482    6         Social protection and risk management
1483    8
1484    4      Financial and private sector development
1485    7                   Social dev/gender/inclusion
1486    8                             Human development
1487    5                         Trade and integration
1488    2                      Public sector governance
1489    8                             Human development
1490   10                             Rural development
1491    6
1492   10                             Rural development
1493   10                             Rural development
1494   10                             Rural development
1495    9                             Urban development
1496    8                             Human development
1497    5                         Trade and integration
1498    4      Financial and private sector development

[1499 rows x 2 columns]

In [56]:
df=pd.DataFrame(mj_df1)

In [57]:
print(df.head())

  code                                   name
0    8                      Human development
1   11
2    1                    Economic management
3    6  Social protection and risk management
4    5                  Trade and integration

In [69]:
mj_group=df.groupby(['name']).count().sort_values(ascending=False, by='code')

In [70]:
print("Top 10 major project themes are as following: " )
print(mj_group)

Top 10 major project themes are as following:
                                              code
name
Environment and natural resources management   223
Rural development                              202
Human development                              197
Public sector governance                       184
Social protection and risk management          158
Financial and private sector development       130
                                               122
Social dev/gender/inclusion                    119
Trade and integration                           72
Urban development                               47
Economic management                             33
Rule of law                                     12

#note: some entries have blank name

In [55]:
## Creat a dic for name and code
theme_dic = {}
for item_list in mj_name:    
    for item in item_list:
        if item['code'] not in theme_dic and item['name'] != "":
            theme_dic[item['code']] = item['name']        

theme_dic

{'8': 'Human development',
 '1': 'Economic management',
 '6': 'Social protection and risk management',
 '5': 'Trade and integration',
 '2': 'Public sector governance',
 '11': 'Environment and natural resources management',
 '7': 'Social dev/gender/inclusion',
 '4': 'Financial and private sector development',
 '10': 'Rural development',
 '9': 'Urban development',
 '3': 'Rule of law'}

In [73]:
# Using the dic iterater over dataframe(df) to map names onto dataframe.
for code in theme_dic:
    df.name[df.code==code]=theme_dic[code]

In [85]:
## Check the code has corect name assignment
print(df.name[df.code=='11'])

1       Environment and natural resources management
6       Environment and natural resources management
16      Environment and natural resources management
28      Environment and natural resources management
31      Environment and natural resources management
37      Environment and natural resources management
63      Environment and natural resources management
64      Environment and natural resources management
65      Environment and natural resources management
70      Environment and natural resources management
78      Environment and natural resources management
81      Environment and natural resources management
82      Environment and natural resources management
83      Environment and natural resources management
84      Environment and natural resources management
85      Environment and natural resources management
98      Environment and natural resources management
101     Environment and natural resources management
102     Environment and natural resources management
104     Environment and natural resources management
105     Environment and natural resources management
108     Environment and natural resources management
110     Environment and natural resources management
111     Environment and natural resources management
118     Environment and natural resources management
126     Environment and natural resources management
127     Environment and natural resources management
133     Environment and natural resources management
135     Environment and natural resources management
136     Environment and natural resources management
                            ...
1284    Environment and natural resources management
1286    Environment and natural resources management
1321    Environment and natural resources management
1324    Environment and natural resources management
1325    Environment and natural resources management
1331    Environment and natural resources management
1343    Environment and natural resources management
1360    Environment and natural resources management
1363    Environment and natural resources management
1376    Environment and natural resources management
1387    Environment and natural resources management
1390    Environment and natural resources management
1402    Environment and natural resources management
1404    Environment and natural resources management
1414    Environment and natural resources management
1419    Environment and natural resources management
1421    Environment and natural resources management
1422    Environment and natural resources management
1423    Environment and natural resources management
1435    Environment and natural resources management
1439    Environment and natural resources management
1445    Environment and natural resources management
1446    Environment and natural resources management
1448    Environment and natural resources management
1449    Environment and natural resources management
1451    Environment and natural resources management
1462    Environment and natural resources management
1465    Environment and natural resources management
1477    Environment and natural resources management
1480    Environment and natural resources management
Name: name, Length: 250, dtype: object

index 1 '11' missing has been filled

In [77]:
mj_group=df.groupby(['name']).count().sort_values(ascending=False, by='code')

In [78]:
print("Top 10 major project themes are as following: " )
print(mj_group)

Top 10 major project themes are as following:
                                              code
name
Environment and natural resources management   250
Rural development                              216
Human development                              210
Public sector governance                       199
Social protection and risk management          168
Financial and private sector development       146
Social dev/gender/inclusion                    130
Trade and integration                           77
Urban development                               50
Economic management                             38
Rule of law                                     15

Done